require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Naming/FileName:
 Exclude:
   - lib/rubocop-petal.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/ExampleLength:
  Enabled: false
