Grape/PreferNamespace:
  Description: 'Prevent usage of namespace aliases.'
  Enabled: true
  StyleGuide: https://github.com/ruby-grape/grape#namespace-validation-and-coercion
  Include:
    - app/api/**/*

Migration/ForeignKeyOption:
  Description: 'Specify the foreign key option to create the constraint.'
  Enabled: true
  Include:
    - db/migrate/**

Migration/SchemaStatementsMethods:
  Description: 'Suggest to use SchemaStatements methods already defined in a migration class.'
  Enabled: true
  Include:
    - db/migrate/**

RSpec/AuthenticatedAs:
  Description: 'Suggest to use authenticated_as instead of legacy api_key.'
  Enabled: true
  Include:
    - spec/api/**/*_spec.rb

RSpec/CreateListMax:
  Description: 'Prevent creating to most records with `FactoryBot.create_list`.'
  Enabled: true
  Max: 5
  Include:
    - spec/**/*

RSpec/SidekiqInline:
  Description: 'Prevent using `Sidekiq::Testing.inline!` in spec in favor of stubbing and calling it inline with `new.perform`.'
  Enabled: pending
  StyleGuide: https://github.com/mperham/sidekiq/issues/3495
  Include:
    - spec/**/*

RSpec/StubProducts:
  Description: 'Suggest to use stub_products instead of veil/unveil_product.'
  Enabled: true
  SafeAutoCorrect: false
  Include:
    - spec/**/*

Grape/HelpersIncludeModule:
  Description: 'Prevent using helpers with block to include module'
  Enabled: true
  Include:
    - app/api/**/*

Grape/UnnecessaryNamespace:
  Description: 'Detect unnecessary usage of Grape namespace.'
  Enabled: true
  Include:
    - app/api/**/*

Rails/EnumPrefix:
  Description: 'Set prefix options when using enums.'
  Enabled: true
  StyleGuide: https://github.com/rails/rails/issues/13389#issue-24527737
  Include:
    - app/models/**/*

Rails/RiskyActiverecordInvocation:
  Description: 'Interpolation, use hash or parameterized syntax.'
  Enabled: true

Rails/TableName:
  Description: 'Prevent usage of table_name= to in favor of convention.'
  Enabled: true
  StyleGuide: "https://rails.rubystyle.guide/#keep-ar-defaults"
  Include:
    - app/models/**/*

Chewy/ResetOnType:
  Description: 'Prevent using reset! methods on Chewy type class'
  Enabled: true
