Grape/HelpersIncludeModule:
  Description: 'Prevent using helpers with block to include module'
  Enabled: true
  Include:
    - app/api/**/*

Grape/UnnecessaryNamespace:
  Description: 'Detect unnecessary usage of Grape namespace.'
  Enabled: true
  Include:
    - app/api/**/*

Rails/EnumPrefix:
  Description: 'Set prefix options when using enums.'
  Enabled: true
  StyleGuide: https://github.com/rails/rails/issues/13389#issue-24527737
  Include:
    - app/models/**/*

Rails/RiskyActiverecordInvocation:
  Description: 'Interpolation, use hash or parameterized syntax.'
  Enabled: true

Rails/TableName:
  Description: 'Prevent usage of table_name= to in favor of convention.'
  Enabled: true
  StyleGuide: "https://rails.rubystyle.guide/#keep-ar-defaults"
  Include:
    - app/models/**/*

Chewy/ResetOnType:
  Description: 'Prevent using reset! methods on Chewy type class'
  Enabled: true
